from pathlib import Path

def write(path, content):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding='utf-8')

files = {
    'LICENSE': '''MIT License\n\nCopyright (c) 2026 PyGiga\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n''',
    'MANIFEST.in': '''include README.md LICENSE requirements.txt setup.py pyproject.toml\nrecursive-include pygiga *.py\nrecursive-include docs *.md\nrecursive-include examples *.py\nrecursive-include tests *.py\n''',
    'pyproject.toml': '''[build-system]\nrequires = ["setuptools>=61.0", "wheel"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "pygiga"\nversion = "0.1.0"\ndescription = "PyGiga AI agent framework."\nauthors = [{ name = "PyGiga" }]\nreadme = "README.md"\nlicense = { file = "LICENSE" }\nrequires-python = ">=3.8"\ndependencies = [\n    "requests>=2.28.0",\n    "grpcio>=1.56.0",\n]\n''',
    'README.md': '''# PyGiga\n\nPyGiga is a modular AI agent framework for managing perception, memory, reasoning, planning, and action.\n\n## Installation\n\n```bash\npip install -e .\n```\n\n## Usage\n\nCreate an AGI instance and ask a prompt:\n\n```python\nfrom pygiga import AGI\n\nagi = AGI()\nresponse = agi.ask(\"Hello world\")\nprint(response)\n```\n''',
    'requirements.txt': '''requests>=2.28.0\ngrpcio>=1.56.0\n''',
    'setup.py': '''from setuptools import setup, find_packages\n\nsetup(\n    name='pygiga',\n    version='0.1.0',\n    description='PyGiga AI agent framework',\n    packages=find_packages(),\n    install_requires=[\n        'requests>=2.28.0',\n        'grpcio>=1.56.0',\n    ],\n    python_requires='>=3.8',\n    include_package_data=True,\n)\n''',
    'docs/api.md': '''# PyGiga API\n\nThis document describes the main public interfaces available in PyGiga.\n\n- `pygiga.AGI` – top-level assistant entrypoint.\n- `pygiga.agents.AgentCoordinator` – controls the perception-memory-reasoning-planning-action pipeline.\n- `pygiga.action.ActionExecutor` – executes actions such as shell commands, browser navigation, filesystem operations, and API calls.\n- `pygiga.communication.ConversationManager` – stores and manages chat history.\n- `pygiga.knowledge.DocumentManager` – stores and retrieves documents.\n- `pygiga.memory.MemoryManager` – exposes short-term, long-term, episodic, working, and semantic memory.\n''',
    'docs/architecture.md': '''# PyGiga Architecture\n\nPyGiga is composed of several layers:\n\n- `agents` – cognitive agent classes that implement perception, memory, reasoning, planning, action, and evaluation.\n- `action` – concrete action modules for executing commands, API requests, browser actions, and more.\n- `communication` – chat and prompt management for agent communication.\n- `knowledge` – document and retrieval stores for knowledge management.\n- `memory` – multiple memory systems for storing and recalling data.\n- `models` – model loader and backend wrapper modules.\n- `perception`, `reasoning`, `planning`, `learning` – domain-specific capabilities for the agent workflow.\n''',
    'examples/assistant.py': '''from pygiga import AGI\n\nif __name__ == '__main__':\n    agi = AGI()\n    result = agi.ask('Hello, PyGiga!')\n    print('Result:', result)\n''',
    'examples/chatbot.py': '''from pygiga.communication import ConversationManager, PromptManager\n\nif __name__ == '__main__':\n    conversation = ConversationManager()\n    prompt_manager = PromptManager()\n    conversation.add_user_message('Hi there!')\n    prompt = prompt_manager.build_text('How are you?', conversation.get_history())\n    print(prompt)\n''',
    'examples/desktop_agent.py': '''from pygiga.agents import ActionAgent\n\nif __name__ == '__main__':\n    agent = ActionAgent()\n    print(agent.info())\n''',
    'examples/robot_agent.py': '''from pygiga.world_model import Environment\n\nif __name__ == '__main__':\n    env = Environment()\n    print(env.info())\n''',
    'examples/web_agent.py': '''from pygiga.api.grpc import GRPCServer\n\nif __name__ == '__main__':\n    server = GRPCServer()\n    print('Server info:', server.info())\n''',
    'pygiga/__init__.py': '''"""PyGiga package."""\n\nfrom .agi import AGI\nfrom .config import Config\nfrom .pipeline import Pipeline\nfrom .runtime import Runtime\n\n__all__ = [\n    'AGI',\n    'Config',\n    'Pipeline',\n    'Runtime',\n]\n\n__version__ = '0.1.0'\n''',
    'pygiga/agi.py': '''"""AGI core orchestrator."""\n\nfrom .agents import AgentCoordinator\n\nclass AGI:\n    """Top-level AGI assistant.""\n\n    def __init__(self):\n        self.coordinator = AgentCoordinator()\n\n    def ask(self, prompt):\n        return self.coordinator.run(prompt)\n\n    def info(self):\n        return {'assistant': 'PyGiga', 'status': 'ready'}\n''',
    'pygiga/config.py': '''"""Configuration helpers."""\n\nimport json\nfrom dataclasses import dataclass, field\nfrom pathlib import Path\nfrom typing import Any, Dict, Optional\n\n@dataclass\nclass Config:\n    app_name: str = 'pygiga'\n    version: str = '0.1.0'\n    debug: bool = False\n    settings: Dict[str, Any] = field(default_factory=dict)\n\n    @classmethod\n    def load(cls, path: Optional[str] = None):\n        config = cls()\n        if path:\n            try:\n                data = json.loads(Path(path).read_text(encoding='utf-8'))\n                config.settings.update(data)\n            except Exception:\n                pass\n        config.settings.update({k: v for k, v in dict(**__import__('os').environ).items()})\n        return config\n''',
    'pygiga/pipeline.py': '''"""Pipeline orchestration."""\n\nclass Pipeline:\n    """Defines a reusable AGI pipeline.""\n\n    def __init__(self, agi=None):\n        self.agi = agi\n\n    def run(self, prompt):\n        if self.agi is None:\n            raise RuntimeError('AGI instance is required')\n        return self.agi.ask(prompt)\n''',
    'pygiga/runtime.py': '''"""Runtime environment for PyGiga."""\n\nfrom .agi import AGI\nfrom .config import Config\n\nclass Runtime:\n    """Application runtime wrapper.""\n\n    def __init__(self, config=None):\n        self.config = config or Config.load()\n        self.agi = AGI()\n        self.running = False\n\n    def start(self):\n        self.running = True\n        print('Runtime started with config:', self.config.settings)\n\n    def stop(self):\n        self.running = False\n        print('Runtime stopped.')\n''',
    'pygiga/learning/feedback.py': '''"""Feedback manager."""\n\nfrom typing import List\n\nclass FeedbackManager:\n    """Collects feedback items.""\n\n    def __init__(self):\n        self.feedback: List[str] = []\n\n    def add(self, message: str):\n        self.feedback.append(message)\n        return {'status': 'added', 'message': message}\n\n    def list(self):\n        return list(self.feedback)\n''',
    'pygiga/tokenizer/__init__.py': '''"""Tokenizer package."""\n\nfrom .ascii import AsciiTokenizer\nfrom .bpe import BPETokenizer\nfrom .embeddings import EmbeddingVectorizer\nfrom .sentencepiece import SentencePieceTokenizer\nfrom .tokenizer import Tokenizer\nfrom .unicode import UnicodeTokenizer\nfrom .vocabulary import Vocabulary\nfrom .wordpiece import WordPieceTokenizer\n\n__all__ = [\n    'AsciiTokenizer',\n    'BPETokenizer',\n    'EmbeddingVectorizer',\n    'SentencePieceTokenizer',\n    'Tokenizer',\n    'UnicodeTokenizer',\n    'Vocabulary',\n    'WordPieceTokenizer',\n]\n''',
    'pygiga/tokenizer/ascii.py': '''"""ASCII tokenizer."""\n\nclass AsciiTokenizer:\n    """Simple ASCII tokenizer.""\n\n    def tokenize(self, text):\n        return [c for c in text]\n\n    def detokenize(self, tokens):\n        return ''.join(tokens)\n''',
    'pygiga/tokenizer/bpe.py': '''"""Byte Pair Encoding tokenizer stub."""\n\nclass BPETokenizer:\n    """Minimal BPE-style tokenizer stub.""\n\n    def tokenize(self, text):\n        return text.split()\n\n    def detokenize(self, tokens):\n        return ' '.join(tokens)\n''',
    'pygiga/tokenizer/embeddings.py': '''"""Embedding utilities."""\n\nfrom typing import List\n\nclass EmbeddingVectorizer:\n    """Generates placeholder vectors.""\n\n    def vectorize(self, text: str):\n        return [float(len(text))]\n\n    def similarity(self, a: List[float], b: List[float]):\n        return 1.0 if a == b else 0.0\n''',
    'pygiga/tokenizer/sentencepiece.py': '''"""SentencePiece tokenizer stub."""\n\nclass SentencePieceTokenizer:\n    """SentencePiece-style tokenizer placeholder.""\n\n    def tokenize(self, text):\n        return text.split()\n\n    def detokenize(self, tokens):\n        return ' '.join(tokens)\n''',
    'pygiga/tokenizer/tokenizer.py': '''"""Base tokenizer."""\n\nfrom .ascii import AsciiTokenizer\n\nclass Tokenizer:\n    """General tokenizer wrapper.""\n\n    def __init__(self):\n        self.inner = AsciiTokenizer()\n\n    def tokenize(self, text):\n        return self.inner.tokenize(text)\n\n    def detokenize(self, tokens):\n        return self.inner.detokenize(tokens)\n''',
    'pygiga/tokenizer/unicode.py': '''"""Unicode tokenizer."""\n\nclass UnicodeTokenizer:\n    """Simple unicode-aware tokenizer.""\n\n    def tokenize(self, text):\n        return text.split()\n\n    def detokenize(self, tokens):\n        return ' '.join(tokens)\n''',
    'pygiga/tokenizer/vocabulary.py': '''"""Vocabulary helper."""\n\nclass Vocabulary:\n    """Stores a simple token vocabulary.""\n\n    def __init__(self):\n        self.tokens = {}\n\n    def add(self, token):\n        self.tokens[token] = self.tokens.get(token, 0) + 1\n\n    def size(self):\n        return len(self.tokens)\n''',
    'pygiga/tokenizer/wordpiece.py': '''"""WordPiece tokenizer stub."""\n\nclass WordPieceTokenizer:\n    """Simple WordPiece placeholder.""\n\n    def tokenize(self, text):\n        return text.split()\n\n    def detokenize(self, tokens):\n        return ' '.join(tokens)\n''',
    'pygiga/tools/__init__.py': '''"""Tools package."""\n\nfrom .calculator import CalculatorTool\nfrom .code import CodeTool\nfrom .registry import ToolRegistry\nfrom .search import SearchTool\nfrom .shell import ShellTool\nfrom .translator import TranslatorTool\nfrom .weather import WeatherTool\n\n__all__ = [\n    'CalculatorTool',\n    'CodeTool',\n    'ToolRegistry',\n    'SearchTool',\n    'ShellTool',\n    'TranslatorTool',\n    'WeatherTool',\n]\n''',
    'pygiga/tools/calculator.py': '''"""Calculator tool."""\n\nimport ast\n\nclass CalculatorTool:\n    """Evaluate simple arithmetic expressions.""\n\n    def calculate(self, expression):\n        try:\n            tree = ast.parse(expression, mode='eval')\n            return eval(compile(tree, '<calc>', mode='eval'), {}, {})\n        except Exception as exc:\n            return {'error': str(exc)}\n''',
    'pygiga/tools/code.py': '''"""Code tool."""\n\nclass CodeTool:\n    """Helper for simple code operations.""\n\n    def format_code(self, code):\n        return code.strip()\n''',
    'pygiga/tools/registry.py': '''"""Tool registry."""\n\nclass ToolRegistry:\n    """Stores tool instances.""\n\n    def __init__(self):\n        self.tools = {}\n\n    def register(self, name, tool):\n        self.tools[name] = tool\n\n    def get(self, name):\n        return self.tools.get(name)\n''',
    'pygiga/tools/search.py': '''"""Search tool."""\n\nclass SearchTool:\n    """Performs simple text searches.""\n\n    def search(self, query, corpus):\n        return [item for item in corpus if query.lower() in item.lower()]\n''',
    'pygiga/tools/shell.py': '''"""Shell tool."""\n\nclass ShellTool:\n    """Placeholder shell command tool.""\n\n    def run(self, command):\n        return {'command': command, 'result': 'stubbed'}\n''',
    'pygiga/tools/translator.py': '''"""Translator tool."""\n\nclass TranslatorTool:\n    """Stub translator.""\n\n    def translate(self, text, target_language='en'):\n        return text\n''',
    'pygiga/tools/weather.py': '''"""Weather tool."""\n\nclass WeatherTool:\n    """Returns placeholder weather data.""\n\n    def forecast(self, location):\n        return {'location': location, 'forecast': 'sunny'}\n''',
    'pygiga/utils/__init__.py': '''"""Utility helpers."""\n\nfrom .cache import Cache\nfrom .config import load_config\nfrom .helpers import safe_get, merge_dicts\nfrom .logger import setup_logger\nfrom .serialization import to_json, from_json\n\n__all__ = [\n    'Cache',\n    'load_config',\n    'safe_get',\n    'merge_dicts',\n    'setup_logger',\n    'to_json',\n    'from_json',\n]\n''',
    'pygiga/utils/cache.py': '''"""Cache utilities."""\n\nclass Cache:\n    """Simple in-memory cache.""\n\n    def __init__(self):\n        self.storage = {}\n\n    def set(self, key, value):\n        self.storage[key] = value\n\n    def get(self, key, default=None):\n        return self.storage.get(key, default)\n\n    def clear(self):\n        self.storage.clear()\n''',
    'pygiga/utils/config.py': '''"""Configuration helpers."""\n\nimport json\nfrom pathlib import Path\n\ndef load_config(path):\n    try:\n        return json.loads(Path(path).read_text(encoding='utf-8'))\n    except Exception:\n        return {}\n''',
    'pygiga/utils/helpers.py': '''"""General helper utilities."""\n\nfrom typing import Any, Dict\n\ndef safe_get(data, key, default=None):\n    if isinstance(data, dict):\n        return data.get(key, default)\n    return default\n\ndef merge_dicts(a: Dict[Any, Any], b: Dict[Any, Any]):\n    result = dict(a)\n    result.update(b)\n    return result\n''',
    'pygiga/utils/logger.py': '''"""Logging setup."""\n\nimport logging\n\ndef setup_logger(name='pygiga', level=logging.INFO):\n    logger = logging.getLogger(name)\n    if not logger.handlers:\n        handler = logging.StreamHandler()\n        formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')\n        handler.setFormatter(formatter)\n        logger.addHandler(handler)\n    logger.setLevel(level)
    return logger\n''',
    'pygiga/utils/serialization.py': '''"""Serialization helpers."""\n\nimport json\n\ndef to_json(value):\n    return json.dumps(value, default=str)\n\ndef from_json(text):\n    return json.loads(text)\n''',
    'pygiga/world_model/__init__.py': '''"""World model package."""\n\nfrom .environment import Environment\nfrom .knowledge_graph import KnowledgeGraph\nfrom .ontology import Ontology\nfrom .simulation import Simulation\nfrom .state import WorldState\n\n__all__ = [\n    'Environment',\n    'KnowledgeGraph',\n    'Ontology',\n    'Simulation',\n    'WorldState',\n]\n''',
    'pygiga/world_model/environment.py': '''"""World environment."""\n\nclass Environment:\n    """Represents a simulation environment.""\n\n    def __init__(self):\n        self.name = 'default'\n\n    def info(self):\n        return {'environment': self.name, 'status': 'initialized'}\n''',
    'pygiga/world_model/knowledge_graph.py': '''"""Knowledge graph."""\n\nclass KnowledgeGraph:\n    """Stores graph nodes and edges.""\n\n    def __init__(self):\n        self.nodes = {}\n        self.edges = []\n\n    def add_node(self, key, data=None):\n        self.nodes[key] = data\n\n    def add_edge(self, source, target):\n        self.edges.append((source, target))\n''',
    'pygiga/world_model/ontology.py': '''"""Ontology manager."""\n\nclass Ontology:\n    """Manages ontology terms.""\n\n    def __init__(self):\n        self.terms = {}\n\n    def add_term(self, name, definition):\n        self.terms[name] = definition\n''',
    'pygiga/world_model/simulation.py': '''"""Simulation engine."""\n\nclass Simulation:\n    """Runs simple world simulations.""\n\n    def __init__(self):\n        self.steps = 0\n\n    def step(self):\n        self.steps += 1\n\n    def status(self):\n        return {'steps': self.steps}\n''',
    'pygiga/world_model/state.py': '''"""World state."""\n\nclass WorldState:\n    """Represents a set of state variables.""\n\n    def __init__(self):\n        self.data = {}\n\n    def set(self, key, value):\n        self.data[key] = value\n\n    def get(self, key, default=None):\n        return self.data.get(key, default)\n''',
    'tests/test_agents.py': '''from pygiga.agents import AgentCoordinator\n\n\ndef test_agent_coordinator_loads():\n    coordinator = AgentCoordinator()\n    assert coordinator is not None\n    assert hasattr(coordinator, 'run')\n''',
    'tests/test_learning.py': '''from pygiga.learning.feedback import FeedbackManager\n\n\ndef test_feedback_manager():\n    manager = FeedbackManager()\n    result = manager.add('Great job')\n    assert result['status'] == 'added'\n    assert manager.list() == ['Great job']\n''',
    'tests/test_memory.py': '''from pygiga.memory.memory_manager import MemoryManager\n\n\ndef test_memory_manager():\n    memory = MemoryManager()\n    assert memory.recall_short() == []\n    memory.remember_short('note')\n    assert memory.recall_short() == ['note']\n''',
    'tests/test_perception.py': '''from pygiga.agents import PerceptionAgent\n\n\ndef test_perception_agent():\n    agent = PerceptionAgent()\n    assert agent is not None\n''',
    'tests/test_planning.py': '''from pygiga.agents import PlanningAgent\n\n\ndef test_planning_agent():\n    agent = PlanningAgent()\n    assert agent is not None\n''',
    'tests/test_reasoning.py': '''from pygiga.agents import ReasoningAgent\n\n\ndef test_reasoning_agent():\n    agent = ReasoningAgent()\n    assert agent is not None\n''',
}

for rel, content in files.items():
    write(rel, content)
    print(f'Wrote {rel}')
